import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-[#D9D9D9]">
          <a
            className="btn btn-ghost normal-case sm:text-3xl flex justify-center items-center font-bold"
            style={{ display: "flex", width: "100%" }}
          >
            Sistem Informasi Pilkades Desa Tarahan
          </a>
        </div>

        {children}
      </body>
    </html>
  );
}
